# -*- coding: utf-8 -*-
"""UAS ICHA AMELIA ANASTASYA 24110310040

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hGVKtv_M5VJwX5aLfWZnat3arMkIQ6jN
"""



import json

# Inisialisasi data inventori
inventory = []

# Fungsi menambahkan data barang
def tambah_barang(nama, stok, harga):
    barang = {
        "nama": nama,
        "stok": stok,
        "harga": harga
    }
    inventory.append(barang)
    print(f"Barang '{nama}' berhasil ditambahkan.\n")

# Fungsi menampilkan daftar barang
def tampilkan_barang():
    print("\n=== Daftar Barang ===")
    if not inventory:
        print("Tidak ada data barang.")
        return
    for i, barang in enumerate(inventory, start=1):
        print(f"{i}. {barang['nama']} - Stok: {barang['stok']} - Harga: Rp{barang['harga']}")
    print()

# Fungsi mengedit data barang
def edit_barang(index, nama=None, stok=None, harga=None):
    try:
        if nama:
            inventory[index]["nama"] = nama
        if stok is not None:
            inventory[index]["stok"] = stok
        if harga is not None:
            inventory[index]["harga"] = harga
        print("Barang berhasil diperbarui.\n")
    except IndexError:
        print("Index barang tidak ditemukan.\n")

# Fungsi menghapus barang
def hapus_barang(index):
    try:
        removed = inventory.pop(index)
        print(f"Barang '{removed['nama']}' berhasil dihapus.\n")
    except IndexError:
        print("Index barang tidak ditemukan.\n")

# Fungsi laporan ringkas
def laporan_ringkas():
    total_barang = sum(barang["stok"] for barang in inventory)
    total_nilai = sum(barang["stok"] * barang["harga"] for barang in inventory)
    print("=== Laporan Ringkas ===")
    print(f"Total Barang: {total_barang}")
    print(f"Total Nilai Inventori: Rp{total_nilai}\n")

# Fungsi menyimpan ke file JSON
def simpan_ke_file(nama_file="inventori.json"):
    with open(nama_file, "w") as file:
        json.dump(inventory, file, indent=4)
    print(f"Data berhasil disimpan ke file '{nama_file}'.\n")

# Fungsi menu utama
def menu():
    while True:
        print("=== MENU INVENTORI ===")
        print("1. Tambah Barang")
        print("2. Tampilkan Daftar Barang")
        print("3. Edit Barang")
        print("4. Hapus Barang")
        print("5. Laporan Ringkas")
        print("6. Simpan ke File")
        print("0. Keluar")
        pilihan = input("Pilih menu (0-6): ")

        if pilihan == "1":
            nama = input("Nama Barang: ")
            stok = int(input("Stok: "))
            harga = int(input("Harga: "))
            tambah_barang(nama, stok, harga)
        elif pilihan == "2":
            tampilkan_barang()
        elif pilihan == "3":
            tampilkan_barang()
            index = int(input("Pilih nomor barang yang ingin diedit: ")) - 1
            nama = input("Nama baru (kosongkan jika tidak diubah): ")
            stok = input("Stok baru (kosongkan jika tidak diubah): ")
            harga = input("Harga baru (kosongkan jika tidak diubah): ")
            edit_barang(index,
                        nama if nama else None,
                        int(stok) if stok else None,
                        int(harga) if harga else None)
        elif pilihan == "4":
            tampilkan_barang()
            index = int(input("Pilih nomor barang yang ingin dihapus: ")) - 1
            hapus_barang(index)
        elif pilihan == "5":
            laporan_ringkas()
        elif pilihan == "6":
            simpan_ke_file()
        elif pilihan == "0":
            print("Terima kasih telah menggunakan sistem inventori.\n")
            break
        else:
            print("Pilihan tidak valid!\n")

# Jalankan program
menu()